<?php

namespace AppBundle\Repository;

/**
 * PeliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeliculaRepository extends \Doctrine\ORM\EntityRepository
{
}
